setup

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -85,44 +85,44 @@ jobs:
           name: wheels
           path: dist/*.whl
 
-  build_windows:
-    name: Build wheels on ${{ matrix.os }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: true
-      matrix:
-        os: [ windows-2019 ]
-        python-version: [ "3.8","3.9","3.10" ]
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install pytest build cython
-          python -m pip install numpy
-          python -m pip install cysignals
-          python -m pip install "cython>=0.29.6"
-      - name: Compile and install
-        run: |
-          python -m pip install . -v
-          ls ${{ github.workspace }}/build || true
-      - name: Test with pytest
-        run: |
-          mv pysdd pysdd_pkg
-          pytest --ignore=venv
-          mv pysdd_pkg pysdd
-      - name: Build
-        run: |
-          python -m build
-      - name: Store wheels
-        uses: actions/upload-artifact@v2
-        with:
-          name: wheels
-          path: dist/*.whl
+#  build_windows:
+#    name: Build wheels on ${{ matrix.os }}
+#    runs-on: ${{ matrix.os }}
+#    strategy:
+#      fail-fast: true
+#      matrix:
+#        os: [ windows-2019 ]
+#        python-version: [ "3.8","3.9","3.10" ]
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up Python ${{ matrix.python-version }}
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#      - name: Install dependencies
+#        run: |
+#          python -m pip install --upgrade pip
+#          python -m pip install pytest build cython
+#          python -m pip install numpy
+#          python -m pip install cysignals
+#          python -m pip install "cython>=0.29.6"
+#      - name: Compile and install
+#        run: |
+#          python -m pip install . -v
+#          ls ${{ github.workspace }}/build || true
+#      - name: Test with pytest
+#        run: |
+#          mv pysdd pysdd_pkg
+#          pytest --ignore=venv
+#          mv pysdd_pkg pysdd
+#      - name: Build
+#        run: |
+#          python -m build
+#      - name: Store wheels
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: wheels
+#          path: dist/*.whl
 
   build_sdist:
     name: Prepare source distribution
